# Generated by Django 2.0.5 on 2018-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='best_score',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
