# Generated by Django 2.0.5 on 2018-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_questions_best_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='best_score',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
